### PR TITLE
Bump QMenuModel to 1.0

### LINKED ISSUE #15: FTBFS: tests/script/dbusmenuscript.h:24:10: fatal error: 'QDBusInterface' file not found
```
[  7%] Building CXX object libqmenumodel/src/CMakeFiles/qmenumodel.dir/qmenumodel_autogen/mocs_compilation.cpp.o
1632cd /rootdir/libqmenumodel/src && /usr/share/clang/scan-build-11/libexec/c++-analyzer -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -Dqmenumodel_EXPORTS -I/rootdir/libqmenumodel/src -I/rootdir/libqmenumodel/src/qmenumodel_autogen/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtQmlModels -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -fPIC -fPIC -fPIC -MD -MT libqmenumodel/src/CMakeFiles/qmenumodel.dir/qmenumodel_autogen/mocs_compilation.cpp.o -MF CMakeFiles/qmenumodel.dir/qmenumodel_autogen/mocs_compilation.cpp.o.d -o CMakeFiles/qmenumodel.dir/qmenumodel_autogen/mocs_compilation.cpp.o -c /rootdir/libqmenumodel/src/qmenumodel_autogen/mocs_compilation.cpp
1633In file included from /rootdir/tests/script/dbusmenuscript.cpp:20:
1634/rootdir/tests/script/dbusmenuscript.h:24:10: fatal error: 'QDBusInterface' file not found
1635#include <QDBusInterface>
1636         ^~~~~~~~~~~~~~~~
16371 error generated.
1638make[2]: *** [tests/script/CMakeFiles/dbusmenuscript.dir/build.make:93: tests/script/CMakeFiles/dbusmenuscript.dir/dbusmenuscript.cpp.o] Error 1
1639make[2]: Leaving directory '/rootdir'
1640make[1]: *** [CMakeFiles/Makefile2:318: tests/script/CMakeFiles/dbusmenuscript.dir/all] Error 2
1641make[1]: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by ghost**
@sunweaver 

Merge this after @peat-psuwit has given his blessing.

fixes https://github.com/AyatanaIndicators/qmenumodel/issues/15

### CODE REVIEW

**Comment by peat-psuwit** [comment]
The changed parts LGTM. Although, if want to keep Debian packaging working, debian/qmenumodel-qml.install has to be updated.

Although, @sunweaver, maybe it's a good idea to use this occasion to rename the QML package name?

**Comment by ghost** [comment]
> The changed parts LGTM. Although, if want to keep Debian packaging working, debian/qmenumodel-qml.install has to be updated.

Done.

> Although, @sunweaver, maybe it's a good idea to use this occasion to rename the QML package name?

qmenumodel-qml.1 or qmenumodel-qml1?

**Comment by peat-psuwit** [comment]
The new package name should be ~~`qml-module-qmenumodel` or perhaps~~ `qml-module-qmenumodel1`, to comply with Debian's QML module package name policy. ~~Although I can't find the mailling list message describe it...~~ https://alioth-lists.debian.net/pipermail/pkg-kde-talk/2014-March/001889.html

**Comment by sunweaver** [comment]
> The changed parts LGTM. Although, if want to keep Debian packaging working, debian/qmenumodel-qml.install has to be updated.
> 
> Although, @sunweaver, maybe it's a good idea to use this occasion to rename the QML package name?

Yes, the qml package should be renamed. I will add a commit to this PR the coming days...

**Comment by sunweaver** [comment]
@tari01 @peat-psuwit please revisit the two new commits I have added. If you are ok with them, I'd merge (and release 0.9.0).

**Comment by peat-psuwit** [comment]
Hmm, the way the rename is done, Breaks/Replaces probably isn't required. The new package installs to a different directory, and thus is co-installable with the old package. Just like different soname versions of a library can be co-installed.

**Comment by sunweaver** [comment]
Hi Ratchanan,

On  Mi 08 Dez 2021 16:31:59 CET, Ratchanan Srirattanamet wrote:

> Hmm, the way the rename is done, Breaks/Replaces probably isn't  
> required. The new package installs to a different directory, and  
> thus is co-installable with the old package. Just like different  
> soname versions of a library can be co-installed.

This is more meant as a cleanup of the old packages. File path wise I  
agree with you.

I can undo the B:/R:.

Mike

-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: ***@***.***, http://das-netzwerkteam.de

**Review by peat-psuwit — APPROVED** [review]
LGTM now.

**Review by mariogrip — APPROVED** [review]

**Comment by ghost** [comment]
@sunweaver 

I have added another commit that fixes the build, we are now good to merge.

**Review by xingwozhonghua126 — APPROVED** [review]

**Review by sunweaver — APPROVED** [review]
ACK, merging...

**Pull request merged**
