### PR TITLE
src/gtk Update gtk part to version 3.24.8

### LINKED ISSUE #22: Update our copy of vendored Gtk files
We vendor a number of files related to GMenuModel and GAction handling from Gtk in commit 4fc790c377f4ca154ea5fc8beca6fd9078edf2ee. Since then, both our copy and Gtk's copy has seen many changes across the years. Maybe it's time to take a look at what could be brought back from Gtk.

I feel like this would be helpful:
https://stackoverflow.com/questions/15959257/how-can-i-generate-apply-git-patches-only-for-commits-that-alter-specific-files

### PR DESCRIPTION
**Pull request by neochapay**
Fixes #22

### CODE REVIEW

**Comment by peat-psuwit** [comment]
I wonder, how do you achieve this? e.g. I can't find any reference to `gtk_menu_tracker_item_update_state()` at all, both in and outside GTK codebase.

**Comment by neochapay** [comment]
@peat-psuwit https://github.com/neochapay/qmenumodel/blob/update_gtk/libqmenumodel/src/gtk/gtkmenutrackeritem.c#L871

**Comment by peat-psuwit** [comment]
I mean, outside of this PR.

**Comment by neochapay** [comment]
@peat-psuwit fixed

**Comment by sunweaver** [comment]
(please re-read here, I updated the comment)

@neochapay for reviewing this in depth, can you provide the Git commit in GTK-3 that references the old state of GTK code in qmenumodel and the Git commit of the version you imported?

It also would have been nice if the GTK code history of the gtk-update in this PR would have stayed in tact (using Git magic). As redoing this with individual original GTK commits by the original developers will cost a considerable amount of time, I'd say we leave it as it is now, but for reviewing I'd appreciate the point in GTK where we stood with the old qmenumodel GTK code and where we will stand after having merged this PR. Thanks.

**Comment by neochapay** [comment]
New gtk state now on version 3.24.8 i use this commit https://gitlab.gnome.org/GNOME/gtk/-/commit/5428379fad31f1637c920d97a3d0303f606bfb6e

current state commit i dont know. If it's critical i`ll need coupe of day to find out

**Pull request merged**
