### PR TITLE
Correct the QMenuModel 1.0 update, fix qmltests (kinda)

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
This PR completes the move of QMenuModel 0.1 to 1.0. It was previously incomplete as QMenuModel was not importable on-device. Also, both `AyatanaMenuModel` and `AyatanaMenuAction` were called `AyatanaMenuAction`.

I noticed that the qmltests were conspicuously passing even though those two items were very obviously named incorrectly and the import could not have worked. Looking at the tests, they mainly checked to see if the test case would crash in case of an action being performed. I'm not sure these tests ever could have failed, even if I fixed the QML, so I removed it all and changed it to an import test.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Hmm, according to [the source code's comment](https://code.woboq.org/qt5/qtdeclarative/src/qml/qml/qqmlimport.cpp.html#526), the `.1` variant should work. In fact, this minimal example does load on UBports (which doesn't contain this PR):

```qml
import QtQml 2.9

import QMenuModel 1.0

QtObject {
    property var x: QDBusActionGroup {}
}
```

I think it's something else that fails Lomiri's load (most likely due to missing change in `debian/control`). Will have a look.

**Comment by peat-psuwit** [comment]
Ok... so with Lomiri fixed (see [1]), the true problem is, indeed, incorrectly named `AyatanaMenuModel`. I'll pick the `AyatanaMenu{Model,Action}` fix to our packaging repo so that Lomiri is fixed. The folder rename is not required.

IMO, you should separate this into 4 PRs:
- `AyatanaMenu{Model,Action}` fix.
- Docs and example fix.
- Test fix.
- Warning fix.

[1] https://gitlab.com/ubports/core/lomiri/-/merge_requests/26
With this MR, the output is:
```
[2021-12-10:16:04:16.476] Lomiri encountered an unrecoverable error while loading:
file:///usr/share/lomiri//ShellApplication.qml:26 Type ShellScreen unavailable
file:///usr/share/lomiri//ShellScreen.qml:50 Type OrientedShell unavailable
file:///usr/share/lomiri//OrientedShell.qml:263 Type Shell unavailable
file:///usr/share/lomiri//Shell.qml:729 Type Notifications unavailable
file:///usr/share/lomiri//Notifications/Notifications.qml:50 Type Notification unavailable
file:///usr/share/lomiri//Notifications/Notification.qml:195 AyatanaMenuModel is not a type
```

**Review by ghost — APPROVED** [review]

**Comment by z3ntu** [comment]
Anything holding this up? Without https://gitlab.com/ubports/core/packaging/qmenumodel/-/blob/main/debian/patches/1001-Fix-naming-of-AyatanaMenuModel-qml-type.patch Lomiri fails to launch with this error
```
[2022-01-16:14:58:25.915] Lomiri encountered an unrecoverable error while loading:
file:///usr/share/lomiri//ShellApplication.qml:26 Type ShellScreen unavailable
file:///usr/share/lomiri//ShellScreen.qml:49 Type OrientedShell unavailable
file:///usr/share/lomiri//OrientedShell.qml:266 Type Shell unavailable
file:///usr/share/lomiri//Shell.qml:729 Type Notifications unavailable
file:///usr/share/lomiri//Notifications/Notifications.qml:50 Type Notification unavailable
file:///usr/share/lomiri//Notifications/Notification.qml:195 AyatanaMenuModel is not a type
```
With the linked patch it works fine.

**Review by sunweaver — APPROVED** [review]
@UniversalSuperBox Thanks for looking into this!

**Pull request merged**
